version: 2

robot:
  model: LOCAL_TEST

network:
  interface: enp2s0

sensors:
  lidar_type: MID360
  lidar_topic: /livox/lidar
  imu_topic: /livox/imu
  scan_lines: 4
  scan_rate: 10
  timestamp_unit: 3
  time_sync_enabled: false
  lidar_to_imu_time_offset: 0.0

geometry:
  body_height: 0.4
  double_cylinder_radius: 0.25
  double_cylinder_offset: 0.18
  obstacles_inflation_z_up: 0.1
  obstacles_inflation_z_down: 0.4

frames:
  base_frame: base_link
  imu_to_base: [0.2, 0.0, 0.0, 0.0, -0.25882, 0.0, -0.96593]
  motion_to_base: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0]
  lidar_to_imu_translation: [-0.011, -0.02329, 0.04412]
  lidar_to_imu_rotation: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

unitree:
  dds_domain_id: 0
  sport_state_topic: rt/sportmodestate

hardware_limits:
  min_vx: -0.3
  max_vx: 0.8
  max_abs_vy: 0.3
  max_abs_vyaw: 0.8
  max_linear_acceleration: 1.0
  max_yaw_acceleration: 1.0

