version: 2

maps:
  outdoor:
    pcd: /home/kangneng/xq/map/pcd/outdoor/outdoor_global_voxel02.pcd
    tomogram: /home/kangneng/xq/code/work_space/kn_nav_ws/src/PCT_planner/rsc/tomogram/outdoor_global_voxel002_ground.pickle
    localization:
      fitness_eval_threshold: 0.2
      tracking_fitness: 0.9
      initial_fitness: 0.9
  cross-floor-kn:
    pcd: /home/kangneng/nav_map/cross-floor-kn/global_map_downsize.pcd
    tomogram: /home/kangneng/nav_map/cross-floor-kn/liuxing_ground_voxel005_radius015.pickle
    localization:
      fitness_eval_threshold: 0.2
      tracking_fitness: 0.7
      initial_fitness: 0.9

