<?xml version="1.0"?>
<package format="3">
  <name>pct_scan_navigation</name>
  <version>0.1.0</version>
  <description>Task coordinator and bringup for PCT with SCAN-Planner.</description>
  <maintainer email="xuqiang656@example.com">xuqiang656</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>scan_planner</exec_depend>
  <exec_depend>fast_lio</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>open3d_loc</exec_depend>
  <exec_depend>pct_planner</exec_depend>
  <exec_depend>pure_pursuit_planner</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
